[project]
name = "parlant-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "parlant>=3.0.2",
    "parlant-client>=3.0.1",
]
